In [1]:
import pandas as pd
thoracic_df = pd.read_csv("C:\\Users\\aoguntuga\\Documents\\DataSets\\thoracic.csv", sep =',',
                          index_col=False,
                          names=['Diagnosis','FVC','FEV1','Zubrod scale',
                                   'Pain before surgery','Haemoptysis before surgery','Dyspnoea before surgery',
                                   'Cough before surgery','Weakness before surgery','T in clinical TNM','Type 2 DM',
                                   'MI up to 6 months','PAD','Smoking','Asthma','Age at surgery','1 year survival period']
                         )
thoracic_df.head()

Diagnosis   FVC  FEV1 Zubrod scale Pain before surgery  \
0      DGN2  2.88  2.16         PRZ1                   F   
1      DGN3  3.40  1.88         PRZ0                   F   
2      DGN3  2.76  2.08         PRZ1                   F   
3      DGN3  3.68  3.04         PRZ0                   F   
4      DGN3  2.44  0.96         PRZ2                   F   

  Haemoptysis before surgery Dyspnoea before surgery Cough before surgery  \
0                          F                       F                    T   
1                          F                       F                    F   
2                          F                       F                    T   
3                          F                       F                    F   
4                          T                       F                    T   

  Weakness before surgery T in clinical TNM Type 2 DM MI up to 6 months PAD  \
0                       T              OC14         F                 F   F   
1                       F              OC12         F                 F   F   
2                       F              OC11         F                 F   F   
3                       F              OC11         F                 F   F   
4                       T              OC11         F                 F   F   

  Smoking Asthma  Age at surgery 1 year survival period  
0       T      F              60                      F  
1       T      F              51                      F  
2       T      F              59                      F  
3       F      F              54                      F  
4       T      F              73                      T

In [2]:
d1 = {'F':0, 'T':1}
d2 = {'PRZ2': 2,'PRZ1':1,'PRZ0':0}
d3 = {'DGN3':3,'DGN2':2,'DGN4':4,'DGN6':6,'DGN5':5,'DGN8':8,'DGN1':1,'DGN7':7}
d4 = {'OC11':1,'OC12':2,'OC13':3,'OC14':4}
thoracic_df['Diagnosis'] = thoracic_df['Diagnosis'].map(d3)
thoracic_df['Zubrod scale'] = thoracic_df['Zubrod scale'].map(d2)
thoracic_df['T in clinical TNM'] = thoracic_df['T in clinical TNM'].map(d4)
thoracic_df['Asthma'] = thoracic_df['Asthma'].map(d1)
thoracic_df['PAD'] = thoracic_df['PAD'].map(d1)
thoracic_df['Smoking'] = thoracic_df['Smoking'].map(d1)
thoracic_df['Cough before surgery'] = thoracic_df['Cough before surgery'].map(d1)
thoracic_df['Weakness before surgery'] = thoracic_df['Weakness before surgery'].map(d1)
thoracic_df['Dyspnoea before surgery'] = thoracic_df['Dyspnoea before surgery'].map(d1)
thoracic_df['Haemoptysis before surgery'] = thoracic_df['Haemoptysis before surgery'].map(d1)
thoracic_df['Pain before surgery'] = thoracic_df['Pain before surgery'].map(d1)
thoracic_df['Type 2 DM'] = thoracic_df['Type 2 DM'].map(d1)
thoracic_df['MI up to 6 months'] = thoracic_df['MI up to 6 months'].map(d1)
thoracic_df['1 year survival period'] = thoracic_df['1 year survival period'].map(d1)

thoracic_df.head()

Diagnosis   FVC  FEV1  Zubrod scale  Pain before surgery  \
0          2  2.88  2.16             1                    0   
1          3  3.40  1.88             0                    0   
2          3  2.76  2.08             1                    0   
3          3  3.68  3.04             0                    0   
4          3  2.44  0.96             2                    0   

   Haemoptysis before surgery  Dyspnoea before surgery  Cough before surgery  \
0                           0                        0                     1   
1                           0                        0                     0   
2                           0                        0                     1   
3                           0                        0                     0   
4                           1                        0                     1   

   Weakness before surgery  T in clinical TNM  Type 2 DM  MI up to 6 months  \
0                        1                  4          0                  0   
1                        0                  2          0                  0   
2                        0                  1          0                  0   
3                        0                  1          0                  0   
4                        1                  1          0                  0   

   PAD  Smoking  Asthma  Age at surgery  1 year survival period  
0    0        1       0              60                       0  
1    0        1       0              51                       0  
2    0        1       0              59                       0  
3    0        0       0              54                       0  
4    0        1       0              73                       1

In [7]:
features = list(thoracic_df.columns[0:16])
X_features = thoracic_df[features].as_matrix()
Y_targets = thoracic_df['1 year survival period'].as_matrix()

In [6]:
X_features

array([[  2.  ,   2.88,   2.16, ...,   1.  ,   0.  ,  60.  ],
       [  3.  ,   3.4 ,   1.88, ...,   1.  ,   0.  ,  51.  ],
       [  3.  ,   2.76,   2.08, ...,   1.  ,   0.  ,  59.  ],
       ..., 
       [  3.  ,   3.04,   2.08, ...,   0.  ,   0.  ,  52.  ],
       [  3.  ,   1.96,   1.68, ...,   1.  ,   0.  ,  79.  ],
       [  3.  ,   4.72,   3.56, ...,   1.  ,   0.  ,  51.  ]])

In [8]:
Y_targets

array([0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0,

In [9]:
import numpy as np
from sklearn import cross_validation,svm

X_train,X_test,y_train,y_test = cross_validation.train_test_split(X_features,Y_targets,test_size = 0.4,random_state=0)

In [10]:
svm_model = svm.SVC(kernel='linear',C=1).fit(X_train,y_train)

In [11]:
svm_model.score(X_test,y_test)

0.8457446808510638

In [12]:
scores = cross_validation.cross_val_score(svm_model,X_features,Y_targets,cv=5)

In [13]:
scores

array([ 0.85106383,  0.85106383,  0.85106383,  0.85106383,  0.85106383])